In [1]:
import torch

In [2]:
A = torch.Tensor([[0,0],[2,0],[1,1],[1,0]])
n = A.shape[0]
print(A)

tensor([[0., 0.],
        [2., 0.],
        [1., 1.],
        [1., 0.]])


In [3]:
A1 = A.T.repeat(n,1,1)
A1

tensor([[[0., 2., 1., 1.],
         [0., 0., 1., 0.]],

        [[0., 2., 1., 1.],
         [0., 0., 1., 0.]],

        [[0., 2., 1., 1.],
         [0., 0., 1., 0.]],

        [[0., 2., 1., 1.],
         [0., 0., 1., 0.]]])

In [4]:
A2 = A[:,:,None].repeat(1,1,n)
A2

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[2., 2., 2., 2.],
         [0., 0., 0., 0.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [0., 0., 0., 0.]]])

In [5]:
A3 = (A2-A1)
A3

tensor([[[ 0., -2., -1., -1.],
         [ 0.,  0., -1.,  0.]],

        [[ 2.,  0.,  1.,  1.],
         [ 0.,  0., -1.,  0.]],

        [[ 1., -1.,  0.,  0.],
         [ 1.,  1.,  0.,  1.]],

        [[ 1., -1.,  0.,  0.],
         [ 0.,  0., -1.,  0.]]])

In [6]:
A3 = A3.transpose(1,2)
A3

tensor([[[ 0.,  0.],
         [-2.,  0.],
         [-1., -1.],
         [-1.,  0.]],

        [[ 2.,  0.],
         [ 0.,  0.],
         [ 1., -1.],
         [ 1.,  0.]],

        [[ 1.,  1.],
         [-1.,  1.],
         [ 0.,  0.],
         [ 0.,  1.]],

        [[ 1.,  0.],
         [-1.,  0.],
         [ 0., -1.],
         [ 0.,  0.]]])

In [7]:
length_of_directions = torch.linalg.norm(A3,dim=-1)
length_of_directions

tensor([[0.0000, 2.0000, 1.4142, 1.0000],
        [2.0000, 0.0000, 1.4142, 1.0000],
        [1.4142, 1.4142, 0.0000, 1.0000],
        [1.0000, 1.0000, 1.0000, 0.0000]])

In [8]:
import torch.nn.functional as F
normed_directions = F.normalize(A3,dim=-1)
normed_directions

tensor([[[ 0.0000,  0.0000],
         [-1.0000,  0.0000],
         [-0.7071, -0.7071],
         [-1.0000,  0.0000]],

        [[ 1.0000,  0.0000],
         [ 0.0000,  0.0000],
         [ 0.7071, -0.7071],
         [ 1.0000,  0.0000]],

        [[ 0.7071,  0.7071],
         [-0.7071,  0.7071],
         [ 0.0000,  0.0000],
         [ 0.0000,  1.0000]],

        [[ 1.0000,  0.0000],
         [-1.0000,  0.0000],
         [ 0.0000, -1.0000],
         [ 0.0000,  0.0000]]])

In [10]:
flows = torch.tensor([[1,0],[1,0],[0,1],[1,0]]).float()
flows

tensor([[1., 0.],
        [1., 0.],
        [0., 1.],
        [1., 0.]])

In [11]:
dot_products = normed_directions*flows
dot_products

tensor([[[ 0.0000,  0.0000],
         [-1.0000,  0.0000],
         [-0.0000, -0.7071],
         [-1.0000,  0.0000]],

        [[ 1.0000,  0.0000],
         [ 0.0000,  0.0000],
         [ 0.0000, -0.7071],
         [ 1.0000,  0.0000]],

        [[ 0.7071,  0.0000],
         [-0.7071,  0.0000],
         [ 0.0000,  0.0000],
         [ 0.0000,  0.0000]],

        [[ 1.0000,  0.0000],
         [-1.0000,  0.0000],
         [ 0.0000, -1.0000],
         [ 0.0000,  0.0000]]])

In [12]:
projections = dot_products.sum(-1)
projections
# rows = destination
# columns = origin

tensor([[ 0.0000, -1.0000, -0.7071, -1.0000],
        [ 1.0000,  0.0000, -0.7071,  1.0000],
        [ 0.7071, -0.7071,  0.0000,  0.0000],
        [ 1.0000, -1.0000, -1.0000,  0.0000]])

In [ ]:
flow_mag = torch.linalg.norm(flows,dim=1)
flow_mag

In [ ]:
flow_mag_directions = flow_mag.repeat(n,1)
flow_mag_directions