In [ ]:
import torch
a = torch.rand(10,2)

In [ ]:
import copy
copy.copy(a)

tensor([[0.0309, 0.6632],
        [0.7177, 0.7729],
        [0.7208, 0.7186],
        [0.8478, 0.9783],
        [0.2358, 0.9450],
        [0.0973, 0.6377],
        [0.3760, 0.2887],
        [0.3563, 0.7361],
        [0.3755, 0.5331],
        [0.7038, 0.9974]])

In [ ]:
torch.flip(a,[0])

tensor([[0.7038, 0.9974],
        [0.3755, 0.5331],
        [0.3563, 0.7361],
        [0.3760, 0.2887],
        [0.0973, 0.6377],
        [0.2358, 0.9450],
        [0.8478, 0.9783],
        [0.7208, 0.7186],
        [0.7177, 0.7729],
        [0.0309, 0.6632]])

In [ ]:
import torch
a = torch.rand(4,4)
torch.max(a)

tensor(0.9574)

In [ ]:
a

tensor([[0.1284, 0.5562, 0.2131, 0.9279],
        [0.1983, 0.0147, 0.3610, 0.7372],
        [0.5342, 0.3589, 0.9574, 0.5749],
        [0.3356, 0.3594, 0.2055, 0.3572]])