In [ ]:
import numpy as np
import scipy

## UW Directed Graph Embedding Algorithm

![UW Directed Embedding Algorithm](../images/UW_directed_embedding_alg.png)

In [ ]:
"""
UW directed embedding algorithm
input: W affinity matrix, m embedding dimension
"""
def UW_directed_embedding(W, m):
    S = (W + np.transpose(W))/2
    q = np.sum(S, axis = 1)
    Q = np.diag(q)
    Qinv = np.linalg.inv(Q)
    V = Qinv@S@Qinv
    q1 = np.sum(V, axis=1)
    Q1 = np.diag(q)
    Q1inv = np.linalg.inv(Q1)
    Hss = Q1inv@V
    eig_vals, eig_vecs = np.linalg.eig(Hss)
    idx = eig_vals.argsort()[::-1]
    eig_vals = eig_vals[idx]
    eig_vecs = eig_vecs[:,idx]
    phi = eig_vecs[:,:(m+1)]
    coords = eig_vecs[:,1:(m+1)]
    A = np.diag(eig_vals)
    
    evals, evecs = scipy.linalg.eig(Hss, left = True, right = False)
    pi = evecs[np.where(evals == 1)]
    density = pi/sum(pi)
    p = np.sum(W, axis = 1)
    P = np.diag(p)
    Pinv = np.linalg.inv(P)
    T = Pinv@W@Pinv
    p1 = np.sum(T, axis = 1)
    P1 = np.diag(p1)
    P1inv = np.linalg.inv(P1)
    Haa = P1@T
    R = ((Haa - Hss)@phi)
    fields = R[:,1:]
    print(np.shape(Haa))
    print(np.shape(R))
    print(np.shape(fields))
    return coords, density, fields

In [ ]:
# Testing Block
S = [[1,0,0,0],
     [1,1,1,0],
     [1,3,0,0],
     [1,2,0,4]]
q = [np.sum(row) for row in S]
Q = np.diag(q)
# print(q)
# print(Q)
# print(Q@S@Q)

eig_vals, eig_vecs = np.linalg.eig(S)
print(eig_vals)
print(eig_vecs)

print("----")

idx = eig_vals.argsort()[::-1]   
eig_vals = eig_vals[idx]
eig_vecs = eig_vecs[:,idx]
phi = eig_vecs[:,:3]
print(eig_vals)
print(phi)

S2 = [[1,0,0],
      [1,0,0],
      [1,0,0]]

S22 = S2 + np.transpose(S2)
# print(S22)


[ 4.          2.30277564 -1.30277564  1.        ]
[[ 0.          0.          0.          0.63799308]
 [ 0.          0.49471995 -0.39390152 -0.42532872]
 [ 0.          0.64450909  0.90706684 -0.63799308]
 [ 1.         -0.5829753   0.14856428  0.07088812]]
----
[ 4.          2.30277564  1.         -1.30277564]
[[ 0.          0.          0.63799308]
 [ 0.          0.49471995 -0.42532872]
 [ 0.          0.64450909 -0.63799308]
 [ 1.         -0.5829753   0.07088812]]
